server:
  port: 16113

spring:
  application:
    name: ts-admin-route-service

swagger:
  controllerPackage: adminroute.controller

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831

logging:
  file:
    name: "myapplog"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false