# HTTP Server
server:
  port: 14322  # HTTP (Tomcat) port

spring:
  application:
    name: ts-travel-plan-service


swagger:
  controllerPackage: travelplan.controller

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 6831

logging:
  file:
    name: "myapplog"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false